travis:
  secure:
    BINSTAR_TOKEN: o47zkb+8YbzAnZ2I3yu10MOjcELC2jAkgcIZSXz028PX82x6qESDbuDV0p6244f1aeEg/k3CZvTeUgyKEq+zRx5gin2owHdoVkuSut+4W20dGnm6crkJ63EWOgOfXKmoX7bvBalL5WGWBMXwX/+lTTEZSx+yPK602I8aohNZXx/PJWMpzoLihcst8/Mv0CSDdcEfm2fC0P1mR5kam85O0fkAowNEppgDVxcalts1jkEk+bnNq0BfGYNWZZ6jklzBW94vpwMNaEOu4kHCSvlsXjuSecsnp1FE3agnW9kAAcyF5sI05qE2JRnEchKYL/wfiA1sNJPMZKrqJ+cpFyQUw+XoWKQYntWgomKONqkkfY8IyCD5kTl7vVU2uvTVJxD1ppWpTmCvJLcopBKhcQRw2oZZsufQilllbzmZ52HgFKHlh3zgtyKmW6cK7VHkuuoiOcXjG17PhgrKKJA/ZuvnBSRPoQZaSBbTcIbHtzuE76LeWTDbCT2hvIyKrYubolRLX45Qth3eePLz8x9aEw4IJBUi12VzcHUPNuIuu/ZFC6xqTnVtZPdTkG+2/KbjCJEate5yPNOYNW/4vQCApsXjdU+YsKtebdIdZwzAJaSVfGTVAafR6CgSvpPaSpoKio/XHEkSIojb2PVcunUurZIRFj2dvmQQlWbfl3xZ5imltYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
